# Generated by Django 3.2.7 on 2021-09-10 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='available_till',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 18, 0, 7, 23759)),
        ),
    ]
