# Generated by Django 3.2.7 on 2021-09-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_form_available_till'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductList',
            new_name='Product',
        ),
        migrations.AlterField(
            model_name='form',
            name='available_till',
            field=models.DateTimeField(default='2021-10-11 09:41:49.444756'),
        ),
    ]
